In [1]:
from models import Dim
from datasets import coil2000
from datetime import datetime
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_columns', None)

## Dimensionality Reduction

In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import rbf_kernel
from sklearn.metrics.pairwise import polynomial_kernel

from sklearn.datasets import make_blobs

X, y = make_blobs(5, n_features=3, centers=4,
                  cluster_std=1, random_state=34)

# dim = Dim()
# dim.X_train = X
# dim.y_train = y

# dim.apply_dim(num_dim=5)


Linear kernel

In [6]:
KXX = np.dot(X, X.T)
l = KXX.shape[0]
j = np.ones(l)
KXX = KXX - (np.dot(np.dot(j, j.T), KXX))/l - (np.dot(KXX, np.dot(j, j.T))) / \
    l + (np.dot((np.dot(j.T, np.dot(KXX, j))), np.dot(j, j.T)))/(np.power(l, 2))

In [70]:
y = np.array([y+1 for y in y])

In [71]:
y

array([[3, 2, 1, 1, 4]])

In [72]:
y = np.reshape(y, (1, y.size))
KYY = np.dot(y.T, y)
print(KYY)
l = KYY.shape[0]
j = np.ones(l)
KYY = KYY - (np.dot(np.dot(j, j.T), KYY))/l - (np.dot(KYY, np.dot(j, j.T))) / \
    l + (np.dot((np.dot(j.T, np.dot(KYY, j))), np.dot(j, j.T)))/(np.power(l, 2))

[[ 9  6  3  3 12]
 [ 6  4  2  2  8]
 [ 3  2  1  1  4]
 [ 3  2  1  1  4]
 [12  8  4  4 16]]


In [61]:
KYY

array([[-0.2,  0.8,  0.8,  0.8, -0.2],
       [ 0.8,  0.8,  0.8,  0.8,  0.8],
       [ 0.8,  0.8,  0.8,  0.8,  0.8],
       [ 0.8,  0.8,  0.8,  0.8,  0.8],
       [-0.2,  0.8,  0.8,  0.8, -0.2]])

In [55]:
np.dot(KXX, KYY)

array([[2742.23000597, 3176.76780853, 3611.30561109, 3611.30561109,
        2307.69220341],
       [4131.41253212, 4308.95125807, 4486.48998402, 4486.48998402,
        3953.87380617],
       [1266.88759736, 2391.14704449, 3515.40649161, 3515.40649161,
         142.62815024],
       [1331.44253349, 2459.78849634, 3588.13445918, 3588.13445918,
         203.09657065],
       [3048.24239089, 3238.34107575, 3428.4397606 , 3428.4397606 ,
        2858.14370603]])

In [32]:
KYY = np.dot(y.T, y)
KYY

array([[14]])

In [ ]:
centered_KYY = KYY - (np.dot(np.dot(j, j.T), KYY))/l - (np.dot(KYY, np.dot(j, j.T))) / \
    l + (np.dot((np.dot(j.T, np.dot(KYY, j))), np.dot(j, j.T)))/(np.power(l, 2))
centered_KYY

In [46]:
rbf_kernel(X.T)a

array([[1.00000000e+00, 9.52063763e-47, 1.71179053e-27],
       [9.52063763e-47, 1.00000000e+00, 1.45449075e-07],
       [1.71179053e-27, 1.45449075e-07, 1.00000000e+00]])

In [3]:
data = coil2000()
dim = Dim(data.train, data.test, data.col_names)
#dim.unpickle_dim('dim/03-23-20:36.pkl')
dim.apply_dim(num_dim=5)
#dim.pickle_dim(datetime.now().strftime('%m-%d-%H:%M'))

('5Dim', 'SLMVP', 'Linear'):   0%|          | 0/1 [00:00<?, ?it/s]

KXX (4657, 4657)
KYY (4657, 4657)


('5Dim', 'KPCA', 'Linear'):   0%|          | 0/1 [00:10<?, ?it/s] 


KeyboardInterrupt: 

In [3]:
dim.get_eigenvalues()

5Dim                                                                \
      SLMVP                 KPCA                                            
     Linear               Linear           Polynomial              Radial   
        Var         %        Var         %        Var         %       Var   
0  0.000215  0.200049  35.284782  0.464525  13.085388  0.441269  0.062245   
1  0.000214  0.199826  14.956229  0.196899   6.224530  0.209905  0.037767   
2  0.000215  0.199928   9.570202  0.125992   3.834091  0.129294  0.030868   
3  0.000215  0.200073   8.760983  0.115339   3.353089  0.113074  0.027196   
4  0.000215  0.200124   7.386654  0.097245   3.156907  0.106458  0.022232   

                                                                              \
                    LOL                     LPP                          LLE   
                                           k=11               k=68-reg=0.001   
          %         Var         %           Var             %            Var   
0  0.345213  294.074063  0.810918  1.422547e-19  7.286049e-01       0.000215   
1  0.209456   35.281034  0.097288  4.587233e-20  2.349505e-01       0.000215   
2  0.171197   14.956223  0.041242  5.038392e-21  2.580581e-02       0.000215   
3  0.150832    9.557407  0.026355  2.077158e-21  1.063886e-02       0.000215   
4  0.123302    8.774792  0.024197  1.652788e-34  8.465308e-16       0.000215   

        
        
        
     %  
0  0.2  
1  0.2  
2  0.2  
3  0.2  
4  0.2

In [3]:
dim.apply_clf()

  0%|          | 0/13 [00:00<?, ?it/s]

XGBoost


100%|██████████| 13/13 [01:07<00:00,  5.17s/it]


# Clustering

In [41]:
# Cluster features
scaler = MinMaxScaler()
scaled_X_T = scaler.fit_transform(dim.X_train.T)
kmeans = KMeans(
    init="random",
    n_clusters=3,
    n_init=10,
    max_iter=300,
    random_state=42
    )
label = kmeans.fit_predict(scaled_X_T)
print(label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 1 0 2 1 0 2 2 2 1 2 2 1 2 0 0 2 2 2 2
 2 2 1 0 1 1 1 2 2 1 2 2 1 2 0 0 1 1 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [11]:
import pandas as pd

df = pd.DataFrame.from_dict(dim.scores, orient='index', columns=['Best Score', 'Params']).reset_index()
df[['Model', 'Dimensions', 'Dim. Technique', 'Dim. Params']] = df["index"].str.split("-", n = 3, expand = True)
df

index  Best Score  \
0   XGBoost-1Dim-SLMVP-Polynomial-Order=5    0.930472   
1               XGBoost-1Dim-SLMVP-Linear    0.930472   
2   XGBoost-1Dim-SLMVP-Radial-Gammas=0.01    0.930472   
3    XGBoost-1Dim-SLMVP-Radial-Gammas=0.1    0.930472   
4      XGBoost-1Dim-SLMVP-Radial-Gammas=1    0.930472   
..                                    ...         ...   
60          XGBoost-50Dim-KPCA-Polynomial    0.927039   
61              XGBoost-50Dim-KPCA-Radial    0.927039   
62                      XGBoost-50Dim-LOL    0.927039   
63                 XGBoost-50Dim-LPP-k=68    0.926180   
64       XGBoost-50Dim-LLE-k=68-reg=0.001    0.928755   

                       Params    Model Dimensions Dim. Technique  \
0    {'xgb__n_estimators': 5}  XGBoost       1Dim          SLMVP   
1    {'xgb__n_estimators': 5}  XGBoost       1Dim          SLMVP   
2    {'xgb__n_estimators': 5}  XGBoost       1Dim          SLMVP   
3    {'xgb__n_estimators': 5}  XGBoost       1Dim          SLMVP   
4    {'xgb__n_estimators': 5}  XGBoost       1Dim          SLMVP   
..                        ...      ...        ...            ...   
60   {'xgb__n_estimators': 5}  XGBoost      50Dim           KPCA   
61   {'xgb__n_estimators': 5}  XGBoost      50Dim           KPCA   
62  {'xgb__n_estimators': 10}  XGBoost      50Dim            LOL   
63  {'xgb__n_estimators': 10}  XGBoost      50Dim            LPP   
64  {'xgb__n_estimators': 10}  XGBoost      50Dim            LLE   

           Dim. Params  
0   Polynomial-Order=5  
1               Linear  
2   Radial-Gammas=0.01  
3    Radial-Gammas=0.1  
4      Radial-Gammas=1  
..                 ...  
60          Polynomial  
61              Radial  
62                None  
63                k=68  
64      k=68-reg=0.001  

[65 rows x 7 columns]

In [13]:
df.sort_values('Best Score').groupby('Dim. Technique', as_index=False).first()

Dim. Technique                                  index  Best Score  \
0           KPCA              XGBoost-50Dim-KPCA-Radial    0.927039   
1            LLE       XGBoost-50Dim-LLE-k=68-reg=0.001    0.928755   
2            LOL                      XGBoost-50Dim-LOL    0.927039   
3            LPP                 XGBoost-50Dim-LPP-k=68    0.926180   
4            PCA                      XGBoost-10Dim-PCA    0.928755   
5          SLMVP  XGBoost-10Dim-SLMVP-Radial-Gammas=0.1    0.924464   

                      Params    Model Dimensions        Dim. Params  
0   {'xgb__n_estimators': 5}  XGBoost      50Dim             Radial  
1  {'xgb__n_estimators': 10}  XGBoost      50Dim     k=68-reg=0.001  
2  {'xgb__n_estimators': 10}  XGBoost      50Dim               None  
3  {'xgb__n_estimators': 10}  XGBoost      50Dim               k=68  
4  {'xgb__n_estimators': 10}  XGBoost      10Dim               None  
5  {'xgb__n_estimators': 10}  XGBoost      10Dim  Radial-Gammas=0.1

In [19]:
x = 'XGBoost-1Dim-KPCA-Linear'
x[8:]

'1Dim-KPCA-Linear'

In [20]:
best_performing = df[df.Dimensions == '1Dim'].sort_values('Best Score')\
    .groupby('Dim. Technique', as_index=False)\
    .first()['index'].to_list()
best_performing = [x[8:] for x in best_performing]

best_performing

['1Dim-KPCA-Linear',
 '1Dim-LLE-k=68-reg=0.001',
 '1Dim-LOL',
 '1Dim-LPP-k=68',
 '1Dim-PCA',
 '1Dim-SLMVP-Polynomial-Order=5']

In [22]:
dim.get_corr_table()[best_performing].to_csv('corr_1dim')

In [9]:
df.groupby(['Dim. Technique']).max('Best Score')

Best Score
Dim. Technique            
KPCA              0.931330
LLE               0.930472
LOL               0.930472
LPP               0.930472
PCA               0.930472
SLMVP             0.931330

# Artificial Dataset

- **n_samples** int, default=100
The number of samples.
- **n_features** int, default=20
The total number of features. These comprise n_informative informative features, n_redundant redundant features, n_repeated duplicated features and n_features-n_informative-n_redundant-n_repeated useless features drawn at random.
- **n_informative** int, default=2
The number of informative features. Each class is composed of a number of gaussian clusters each located around the vertices of a hypercube in a subspace of dimension n_informative. For each cluster, informative features are drawn independently from N(0, 1) and then randomly linearly combined within each cluster in order to add covariance. The clusters are then placed on the vertices of the hypercube.
- **n_redundant** int, default=2
The number of redundant features. These features are generated as random linear combinations of the informative features.
- **n_repeated** int, default=0
The number of duplicated features, drawn randomly from the informative and the redundant features.
- **n_classes** int, default=2
The number of classes (or labels) of the classification problem.
- **n_clusters_per_class** int, default=2
The number of clusters per class.
- **weights** array-like of shape (n_classes,) or (n_classes - 1,), default=None
The proportions of samples assigned to each class. If None, then classes are balanced. Note that if len(weights) == n_classes - 1, then the last class weight is automatically inferred. More than n_samples samples may be returned if the sum of weights exceeds 1. Note that the actual class proportions will not exactly match weights when flip_y isn’t 0.
- **flip_y** float, default=0.01
The fraction of samples whose class is assigned randomly. Larger values introduce noise in the labels and make the classification task harder. Note that the default setting flip_y > 0 might lead to less than n_classes in y in some cases.
- **class_sep** float, default=1.0
The factor multiplying the hypercube size. Larger values spread out the clusters/classes and make the classification task easier.
- **hypercube** bool, default=True
If True, the clusters are put on the vertices of a hypercube. If False, the clusters are put on the vertices of a random polytope.
- **shift** float, ndarray of shape (n_features,) or None, default=0.0
Shift features by the specified value. If None, then features are shifted by a random value drawn in [-class_sep, class_sep].
- **scale** float, ndarray of shape (n_features,) or None, default=1.0
Multiply features by the specified value. If None, then features are scaled by a random value drawn in [1, 100]. Note that scaling happens after shifting.
- **shuffle** bool, default=True
Shuffle the samples and the features.
- **random_state** int, RandomState instance or None, default=None
Determines random number generation for dataset creation. Pass an int for reproducible output across multiple function calls. See Glossary.

In [1]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(n_samples=1000, n_features=300, n_informative=4, n_redundant=296, random_state=5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=33)
